"use strict";

/** Generated by Serverless WarmUp Plugin at 2019-07-08T16:19:01.357Z */
const aws = require("aws-sdk");
aws.config.region = "us-east-1";
const lambda = new aws.Lambda();
const functions = [{"name":"lesspod-22-dev-nuxt-renderer","config":{"enabled":true,"payload":"{\"source\":\"serverless-plugin-warmup\"}","concurrency":1}}];

module.exports.warmUp = async (event, context) => {
  console.log("Warm Up Start");
  
  const invokes = await Promise.all(functions.map(async (func) => {
    console.log(`Warming up function: ${func.name} with concurrency: ${func.config.concurrency}`);
    
    const params = {
      ClientContext: Buffer.from(`{"custom":${func.config.payload}}`).toString('base64'),
      FunctionName: func.name,
      InvocationType: "RequestResponse",
      LogType: "None",
      Qualifier: process.env.SERVERLESS_ALIAS || "$LATEST",
      Payload: func.config.payload
    };
    
    try {
      await Promise.all(Array(func.config.concurrency).fill(0).map(async () => await lambda.invoke(params).promise()));
      console.log(`Warm Up Invoke Success: ${func.name}`);
      return true;
    } catch (e) {
      console.log(`Warm Up Invoke Error: ${func.name}`, e);
      return false;
    }
  }));

  console.log(`Warm Up Finished with ${invokes.filter(r => !r).length} invoke errors`);
}